### ISSUE TITLE
DynamicSupervisor tutorial errors because it has no child_spec.

### ISSUE THREAD

**Issue by thebriz24** [elixir-lang/elixir-lang.github.com#1090]
```
defmodule KV.Supervisor do
  use Supervisor

  def start_link(opts) do
    Supervisor.start_link(__MODULE__, :ok, opts)
  end

  def init(:ok) do
    children = [
      {KV.Registry, name: KV.Registry},
      {DynamicSupervisor, name: KV.BucketSupervisor, strategy: :one_for_one}
    ]

    Supervisor.init(children, strategy: :one_for_one)
  end
end 
```

Yeilds:

```
 ** (Mix) Could not start application queue: KV.start(:normal, []) returned an error: an exception was raised:
    ** (ArgumentError) The module DynamicSupervisor was given as a child to a supervisor
but it does not implement child_spec/1.

If you own the given module, please define a child_spec/1 function
that receives an argument and returns a child specification as a map.
For example:

    def child_spec(opts) do
      %{
        id: __MODULE__,
        start: {__MODULE__, :start_link, [opts]},
        type: :worker,
        restart: :permanent,
        shutdown: 500
      }
    end

Note that "use Agent", "use GenServer" and so on automatically define
this function for you.

However, if you don't own the given module and it doesn't implement
child_spec/1, instead of passing the module name directly as a supervisor
child, you will have to pass a child specification as a map:

    %{
      id: DynamicSupervisor,
      start: {DynamicSupervisor, :start_link, [arg1, arg2]}
    }

See the Supervisor documentation for more information.

        (elixir) lib/supervisor.ex:632: Supervisor.init_child/1
        (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
        (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
        (elixir) lib/supervisor.ex:618: Supervisor.init/2
        (stdlib) supervisor.erl:294: :supervisor.init/1
        (stdlib) gen_server.erl:365: :gen_server.init_it/2
        (stdlib) gen_server.erl:333: :gen_server.init_it/6
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

I'm sure there's a way around it but the tutorial said it should just work out of the box.

**Comment by michalmuskala** [comment]
Yes, this function was accidentally not included in 1.6.0, but it was introduced in 1.6.1. Please upgrade your elixir version and it should work fine.

**Comment by thebriz24** [comment]
Bueno. Thank you very much.

**Comment by ysmood** [comment]
I have the same issue for the latest version of elixir

```
$ elixir --version
Erlang/OTP 21 [erts-10.2.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.8.1 (compiled with Erlang/OTP 21)

$ iex -S mix      
Erlang/OTP 21 [erts-10.2.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

Interactive Elixir (1.8.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> DynamicSupervisor.start_child(KV.BucketSupervisor, KV.Bucket)
** (ArgumentError) The module KV.Bucket was given as a child to a supervisor
but it does not implement child_spec/1.

If you own the given module, please define a child_spec/1 function
that receives an argument and returns a child specification as a map.
For example:

    def child_spec(opts) do
      %{
        id: __MODULE__,
        start: {__MODULE__, :start_link, [opts]},
        type: :worker,
        restart: :permanent,
        shutdown: 500
      }
    end

Note that "use Agent", "use GenServer" and so on automatically define
this function for you.

However, if you don't own the given module and it doesn't implement
child_spec/1, instead of passing the module name directly as a supervisor
child, you will have to pass a child specification as a map:

    %{
      id: KV.Bucket,
      start: {KV.Bucket, :start_link, [arg1, arg2]}
    }

See the Supervisor documentation for more information.

    (elixir) lib/supervisor.ex:629: Supervisor.init_child/1
    (elixir) lib/supervisor.ex:733: Supervisor.child_spec/2
    (elixir) lib/dynamic_supervisor.ex:320: DynamicSupervisor.start_child/2 
iex(1)> 
```

**Comment by VincentBlackdot** [comment]
hey was this issue ever fixed i have the same error i am unsinging 

Erlang/OTP 22 [erts-10.7] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]

Elixir 1.10.4 (compiled with Erlang/OTP 21)
