### ISSUE TITLE
 Chapter 6 - ETS tests don't pass

### ISSUE THREAD

**Issue by romenigld** [elixir-lang/elixir-lang.github.com#1191]
I'm reading the Chapter 6 - ETS of the Mix and OTP.
And when I do the part of the creating a “bogus” bucket, which is a synchronous request, after Agent.stop/2.
```
  test "removes buckets on exit", %{registry: registry} do
    KV.Registry.create(registry, "shopping")
    {:ok, bucket} = KV.Registry.lookup(registry, "shopping")
    Agent.stop(bucket)

    # Do a call to ensure the registry processed the DOWN message
    _ = KV.Registry.create(registry, "bogus")
    assert KV.Registry.lookup(registry, "shopping") == :error
  end

  test "removes bucket on crash", %{registry: registry} do
    KV.Registry.create(registry, "shopping")
    {:ok, bucket} = KV.Registry.lookup(registry, "shopping")

    # Stop the bucket with non-normal reason
    Agent.stop(bucket, :shutdown)
    
    # Do a call to ensure the registry processed the DOWN message
    _ = KV.Registry.create(registry, "bogus")
    assert KV.Registry.lookup(registry, "shopping") == :error
  end
```
There tells me the test should pass.. (`Our tests should now (always) pass!`)
But my test not pass. I get a error and I think the information error is weird it's not the same in order like the book tutorial. 
```
mix test --trace

KV.BucketTest
  * test stores values by key (0.1ms)y key
  * test delete a key from the bucket (2002.0ms)lete a key from the bucket
  * test are temporary workers (0.2ms)            * test are temporary workers

                                      KV.RegistryTest
  * test spawns buckets (5005.5ms)                     * test spawns buckets

                                    1) test spawns buckets (KV.RegistryTest)
                                                                                 test/kv/registry_test.exs:10
          ** (exit) exited in: GenServer.call(:"test spawns buckets", {:create, "shopping"}, 5000)
                                                                                                           ** (EXIT) time out
                          code: KV.Registry.create(registry, "shopping")
                                                                             stacktrace:
                                                                                               (elixir) lib/gen_server.ex:924: GenServer.call/3
                                              test/kv/registry_test.exs:13: (test)

                                                                                    * test removes bucke  * test removes buckets on exit (5001.1ms)

                                             2) test removes buckets on exit (KV.RegistryTest)
                                                                                                   test/kv/registry_test.exs:20
                            ** (exit) exited in: GenServer.call(:"test removes buckets on exit", {:create, "shopping"}, 5000)
                              ** (EXIT) time out
                                                     code: KV.Registry.create(registry, "shopping")
                                                                                                        stacktrace:
                  (elixir) lib/gen_server.ex:924: GenServer.call/3
                                                                         test/kv/registry_test.exs:21: (test)

  * test removes bucket on crash (5000.6ms)

                                             3) test removes bucket on crash (KV.RegistryTest)
                                                                                                   test/kv/registry_test.exs:30
                            ** (exit) exited in: GenServer.call(:"test removes bucket on crash", {:create, "shopping"}, 5000)
                              ** (EXIT) time out
                                                     code: KV.Registry.create(registry, "shopping")
                                                                                                        stacktrace:
                  (elixir) lib/gen_server.ex:924: GenServer.call/3
                                                                         test/kv/registry_test.exs:31: (test)


     KVTest


           Finished in 17.0 seconds
                                   6 tests, 3 failures

                                                      Randomized with seed 29245
```

So my versions is Elixir 1.7.4 and Erlang 21.1.1.
I'm posting the code on my [GitHub Account](https://github.com/romenigld/mix-and-otp)

**Comment by romenigld** [comment]
Hello Jose Valim,
thank's for reply.
I remove them and the error was this:
```
mix test --trace
Compiling 1 file (.ex)

KV.BucketTest
  * test delete a key from the bucket (0.1ms)
  * test are temporary workers (0.05ms)
  * test stores values by key (0.07ms)

KV.RegistryTest
  * test removes buckets on exit (5004.0ms)

  1) test removes buckets on exit (KV.RegistryTest)
     test/kv/registry_test.exs:20
     ** (exit) exited in: GenServer.call(:"test removes buckets on exit", {:create, "shopping"}, 5000)
         ** (EXIT) time out
     code: KV.Registry.create(registry, "shopping")
     stacktrace:
       (elixir) lib/gen_server.ex:924: GenServer.call/3
       test/kv/registry_test.exs:21: (test)

  * test removes bucket on crash (5000.9ms)

  2) test removes bucket on crash (KV.RegistryTest)
     test/kv/registry_test.exs:30
     ** (exit) exited in: GenServer.call(:"test removes bucket on crash", {:create, "shopping"}, 5000)
         ** (EXIT) time out
     code: KV.Registry.create(registry, "shopping")
     stacktrace:
       (elixir) lib/gen_server.ex:924: GenServer.call/3
       test/kv/registry_test.exs:31: (test)

  * test spawns buckets (5000.9ms)

  3) test spawns buckets (KV.RegistryTest)
     test/kv/registry_test.exs:10
     ** (exit) exited in: GenServer.call(:"test spawns buckets", {:create, "shopping"}, 5000)
         ** (EXIT) time out
     code: KV.Registry.create(registry, "shopping")
     stacktrace:
       (elixir) lib/gen_server.ex:924: GenServer.call/3
       test/kv/registry_test.exs:13: (test)


KVTest


Finished in 15.0 seconds
6 tests, 3 failures
```
