### ISSUE TITLE
[Bug]  tutorial is out of date?

### ISSUE THREAD

**Issue by Guang1234567** [elixir-lang/elixir-lang.github.com#1252]
Hello dev:

i just write a demo under the [tutorial](https://elixirschool.com/en/lessons/ecto/basics/#creating-a-repository)

```
defmodule Example.Repo do
  use Ecto.Repo, otp_app: :friends
end
```

but get the below error:

https://github.com/elixir-lang/elixir-lang.github.com/issues/1090#issuecomment-469143778

```ruby
$ elixir --version
Erlang/OTP 21 [erts-10.2.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.8.1 (compiled with Erlang/OTP 21)

$ iex -S mix      
Erlang/OTP 21 [erts-10.2.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

Interactive Elixir (1.8.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> DynamicSupervisor.start_child(KV.BucketSupervisor, KV.Bucket)
** (ArgumentError) The module KV.Bucket was given as a child to a supervisor
but it does not implement child_spec/1.

If you own the given module, please define a child_spec/1 function
that receives an argument and returns a child specification as a map.
For example:

    def child_spec(opts) do
      %{
        id: __MODULE__,
        start: {__MODULE__, :start_link, [opts]},
        type: :worker,
        restart: :permanent,
        shutdown: 500
      }
    end

Note that "use Agent", "use GenServer" and so on automatically define
this function for you.

However, if you don't own the given module and it doesn't implement
child_spec/1, instead of passing the module name directly as a supervisor
child, you will have to pass a child specification as a map:

    %{
      id: KV.Bucket,
      start: {KV.Bucket, :start_link, [arg1, arg2]}
    }

See the Supervisor documentation for more information.

    (elixir) lib/supervisor.ex:629: Supervisor.init_child/1
    (elixir) lib/supervisor.ex:733: Supervisor.child_spec/2
    (elixir) lib/dynamic_supervisor.ex:320: DynamicSupervisor.start_child/2 
iex(1)>

```

So i fix the this bug like below: 

```elixir
defmodule Example.Repo do
  use Ecto.Repo, otp_app: :friends

  def child_spec(opts) do
    %{
      id: Example_Repo_child_spec,
      start: {__MODULE__, :start_link, [opts]},
      shutdown: 5_000,
      restart: :permanent,
      type: :worker
    }
  end

end
```

or

https://github.com/elixir-ecto/ecto/blob/d7e8e7ac76610b35dacd4c9f4e63ca2316e66202/examples/friends/lib/friends.ex#L1-L21

> Play a attension, I use `ecto  2.X` and  `ecto_mnesia 0.9.0`,    not `ecto  3.X`

```Elixir
defp deps do
    [
      # {:dep_from_hexpm, "~> 0.3.0"},
      # {:dep_from_git, git: "https://github.com/elixir-lang/my_dep.git", tag: "0.1.0"},
      # {:sibling_app_in_umbrella, in_umbrella: true}
      {:ecto, "~> 2.0"},
      #{:postgrex, "~> 0.11"}
      {:ecto_mnesia, "~> 0.9.0"}
    ]
  end
```

```Elixir
defmodule Friends.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    import Supervisor.Spec

    # List all child processes to be supervised
    children = [
      # Starts a worker by calling: Friends.Worker.start_link(arg)
      # {Friends.Worker, arg}


      supervisor(Example.Repo, [])
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Friends.Supervisor]
    Supervisor.start_link(children, opts)
  end
end
```

Question:

Is the tutorial out of date or `Ecto’s bug`?

**Comment by josevalim** [comment]
I believe the tutorial is out of date. If you are following the tutorial on ElixirSchool, you can start a discussion here: https://github.com/elixirschool/elixirschool Thank you!
